### ISSUE TITLE
Behavior when re-opening the same bucket with different options

### ISSUE THREAD

**Issue by asakusuma** [WICG/storage-buckets#35]
Given the [Separate intents for creating a bucket and opening an existing bucket](https://github.com/WICG/storage-buckets/blob/gh-pages/explainer.md#separate-intents-for-creating-a-bucket-and-opening-an-existing-bucket) section in the explainer, what would happen in the following scenario?
```JavaScript
const draftsBucket = await navigator.storageBuckets.open("drafts", {
    durability: "strict", persisted: true });
const duplicateDraftsBucket = await navigator.storageBuckets.open("drafts", {
    durability: "relaxed", persisted: false });
```

Would the new options be ignored, or would we update the bucket with new options? I would lean towards the later. If we ignore new options, we should probably throw.

**Comment by evanstade** [comment]
This is tricky because some of the attributes can be changed, and some cannot. `quota` and `durability` can't change, so I would expect those to be ignored when an existing bucket is being retrieved. But should `persisted` and `expiration` be updated, when provided, or ignored?

Given the text below, I think the policies that /can/ be updated /should/ be updated. (That is, `persisted` and `expiration`.)

> We want applications to be written assuming that each time they attempt to open a bucket, they may be creating the bucket from scratch.

Those policies that can't be updated should simply be **silently ignored**. The justification for this is that the user agent is already allowed to ignore most policies at initial creation time:

> A quota argument passed to open is a hint, and user agents may choose not to follow it.

> The durability policy can be queried at any time. The user agent may not honor the policy requested by the open() call.

> The persistence policy can be queried at any time. The user agent may decline a persisted: true policy requested by open().
