### ISSUE TITLE
Storage bucket quota questions

### ISSUE THREAD

**Issue by zeroliu** [WICG/storage-buckets#4]
**Reserving quota**
Need more clarification on the behavior of reserving a quota. I assume it pre-occupies certain amount of disk space and the reserved space is not accessible by other buckets/origins/applications. It's not clear to me how it would work together with browser eviction. For example:

Stage 0: free disk space 500MB.
Stage 1: bucketA reserves 100MB. free disk space becomes 400MB (or should it be 500MB?).
Stage 2: bucketB stores 400MB worth of data. Should eviction kicks in? What's being evicted?

**Missing maxQuota policy**
The [original proposal](https://docs.google.com/presentation/d/143w70xtfqculs5x-bPgTOwu6GZO6uTOYeBjnN63pzs8/edit?urp=gmail_link&gxids=7628#slide=id.g635d02e074_0_11) has a `maxQuota` policy. It's no longer available in the explainer. Has it been removed?

**Bucket storage estimate API**
What quota does the estimate API returns? If it accurately reflect free space made available to a storage bucket, would it resurrect the [side channel security bug](https://bugs.chromium.org/p/chromium/issues/detail?id=960305)?

**Comment by zeroliu** [comment]
Following up on the latest code explainer:

There is a section about checking storage estimate quota to stop downloading video.

```
const offlineVideosEstimate = await offlineVideosBucket.estimate();
if (offlineVideosEstimate.usage >= offlineVideosEstimate.quota * 0.95) {
  displayWarningButterBar("Delete old downloaded videos to download more");
}
```

The `offlineVideosBucket` is not created with a fixed quota. How can we estimate its size accurately without causing the finger printing security issue? Chrome prevented it by not revealing free space in the estimated result. Isn't this example reverting the protection?

**Comment by ayuishii** [comment]
Hi @zeroliu !
This is correct, “estimate” may not be an accurate representation of how much free space is left, but reflects available quota. Therefore this example does not change the privacy aspect of the estimate() API. In the future, we hope that the  [Storage Pressure Event](https://github.com/jarryd999/storage-pressure-event) will be a good way to avoid errors on write due to low disk space.

**Comment by evanstade** [comment]
Not sure what the explainer had to say when this issue was originally filed, but now it says:

> A bucket’s quota policy allows setting a per-bucket quota which can be used to place an upper bound on storage usage for each application feature. This ensures that a bug in an application feature won’t impact another feature’s ability to store data by eating up the entire origin’s quota.

> A quota argument passed to open is a hint, and user agents may choose not to follow it.

I think it's (sufficiently?) clear that there is no way to "reserve" a certain amount of space for a bucket. So to answer:

> Stage 2: bucketB stores 400MB worth of data. Should eviction kicks in? What's being evicted?

in reality, the origin (bucketB + other buckets) would not be allowed to use up that large a percent of the free disk space. But if instead of "free disk space" we change the 500MB figure to represent "available quota for the origin" then no, nothing happens, because bucketA only specified an _upper bound_ and didn't reserve anything.
