### ISSUE TITLE
Expose `StorageBucket.name`

### ISSUE THREAD

**Issue by tomayac** [WICG/storage-buckets#42]
Intuitively I would have expected a `delete()` method per `StorageBucket`, vs. the current `StorageBucketManager.delete()` way, which relies on the name of the bucket, which, to my surprise, is also not exposed as `StorageBucket.name`.

**Comment by evanstade** [comment]
`open` is intentionally agnostic as to whether the bucket already exists. For symmetry, `delete` should be as well. If `delete` were a method on the bucket itself, this could require creating a bucket just to delete it.

Exposing the name makes sense and the lack of it was probably an oversight.

**Comment by asutherland** [comment]
I agree that it makes sense to expose the name and that it's desirable to avoid exposing a `delete(void)` method on `StorageBucket` because:
- The cited avoidance of a foot-gun idiom of opening a bucket just to delete it.  (Most important.)
- Consistency with [CacheStorage.delete](https://w3c.github.io/ServiceWorker/#cache-storage-delete) which does not have a corresponding equivalent method on Cache.  There is a [Cache.delete](https://w3c.github.io/ServiceWorker/#cache-delete) method but that is explicitly not about deleting the Cache itself but rather requests stored in the Cache, not the existence of the Cache itself.
- Consistency with IndexedDB where [IDBDatabase](https://w3c.github.io/IndexedDB/#database-interface) exposes createObjectStore and deleteObjectStore but where [IDBObjectStore](https://w3c.github.io/IndexedDB/#object-store-interface) does not expose any method to delete itself, but does expose:
   - delete(query) which is about contained keys/value (not the object store itself)
   - createIndex and deleteIndex to deal with [IDBIndex](https://w3c.github.io/IndexedDB/#index-interface)es and where that interface also does not expose a self-delete mechanism.
- The eager deletion semantics for buckets is important but also potentially a foot-gun for multiple concurrent users of a bucket.  I could imagine system handing a bucket to a subsystem for use and where the bucket is to be deleted when it's done being used.  If `delete()` were on the bucket it might bias the idiom to have the subsystem delete the bucket via that method rather than having the subsystem return a Promise that it could resolve when it's done with the bucket.  In the event multiple subsystems need to work in the bucket, only a minimal change is required for the Promise-returning idiom to use Promise.all() rather than to change the behavior inside the subsystem.

**Comment by tomayac** [comment]
Thanks for the feedback, understood the motivation. Let me refocus this Issue then on exposing `StorageBucket.name`.
