### ISSUE TITLE
Why is persisted nullable?

### ISSUE THREAD

**Issue by annevk** [WICG/storage-buckets#97]
It's used as a boolean in prose, not as a tri-state.

**Comment by ayuishii** [comment]
Thanks for the catch! Spec updated in #106.
Filed a chromium bug to update here: https://crbug.com/1488942

**Comment by evanstade** [comment]
Reopening this as I have some questions about this guidance.

As this is something we persist to disk, the tri-state ("false", "true", "use default") does have slightly different semantics than a binary. For example, we might add nested buckets later on that inherit policies from ancestors, or we might for some unfortunate reason desire to change default behavior. In these cases, "use default" is useful to keep around and distinct from "false" or "true". On top of that, keeping it optional in the IDL would be required for us to log detailed usage metrics (that distinguish "unspecified" from the default).

Are there downsides to leaving dictionary members optional, even when the spec defines a default behavior?

The [design principles document](https://w3ctag.github.io/design-principles/#optional-parameters) is slightly ambiguous on this topic, by my reading, because it suggests optional parameters, and optional dictionaries full of parameters, but is silent on the topic of whether members of optional dictionary arguments should themselves be optional.

**Comment by annevk** [comment]
The specification should essentially describe the simplest model that works. User agents might have more complicated implementations for metric reasons or performance, but that shouldn't impact the model we all end up agreeing on.

The note in https://infra.spec.whatwg.org/#algorithm-conformance attempts to capture this idea.

This doesn't preclude us from making the model more complicated at a later point to tackle new scenarios that are web observable, of course. And we should ensure that our current model allows for such anticipated changes, but preemptively designing for a future that's not yet here is almost never the way to go.

**Comment by evanstade** [comment]
Is the IDL part of what you term the model or the implementation? The IDL is, it seems, an implementation detail --- our exact IDL ties our hands with respect to metrics, but AFAIU we have to match what's in the spec.

>  preemptively designing for a future that's not yet here is almost never the way to go.

I agree with this philosophy, in the sense that adding prospective complexity would be a bad idea. But the design principles document does admit concern for the future in scenarios that are simple to accommodate: 

> API methods should generally use dictionary arguments instead of a series of optional arguments. [...] It also makes the API more extensible in the future, particularly if multiple arguments with the same type are needed."

Which makes it sound like format of method arguments is one of the places where it's worthwhile to consider the future, and I wouldn't have thought that either decision here would lead to meaningfully greater complexity.

**Comment by annevk** [comment]
IDL describes (part of) the public API for the model.

And no, implementations typically have IDL that is more involved than the specification, for a variety of reasons, but implementations aim to never be different in a web observable manner. So if Chromium wants to default to true outside of IDL for metric reasons it certainly can, as nobody will be able to tell the difference (assuming you implement it correctly).

**Comment by evanstade** [comment]
Alright, thanks for explaining. Misunderstanding on my end wrt the function of the spec's IDL,
